services:
  postgres:
    build: .
    environment:
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogdb
      - POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloguser -d blogdb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Service pour les migrations Prisma (optionnel en dev)
  prisma:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://bloguser:password@postgres:5432/blogdb
    depends_on:
      postgres:
        condition: service_healthy
    command: |
      sh -c "
        npm install &&
        npx prisma migrate deploy &&
        npx prisma generate &&
        npx prisma db seed
      "
    profiles:
      - tools

  # Interface Prisma Studio (optionnel)
  studio:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://bloguser:password@postgres:5432/blogdb
    depends_on:
      - postgres
    command: |
      sh -c "
        npm install &&
        npx prisma studio --hostname 0.0.0.0
      "
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local